# No filter dataset through the CNN

In [47]:
import numpy as np
import pandas as pd
import os
import cv2
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from PIL import Image
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import accuracy_score
np.random.seed(42)

from matplotlib import style
style.use('fivethirtyeight')

In [48]:
training_data2 = np.load('30_original_train_data.npy')
training_label2 = np.load('30_original_train_labels.npy')

In [49]:
training_label2

array([26, 15, 13, ..., 39,  1, 10])

In [50]:
john_label = np.load('john_label_vec.npy')
john_data = np.load('john_data_vec.npy')

In [51]:
NUM_CATEGORIES = 43
IMG_HEIGHT =30
IMG_WIDTH=30
channels =3

In [52]:
john_data.shape

(39209, 30, 30, 3)

In [64]:
john_data

array([[[[ 42,  59, 106],
         [ 39,  54,  95],
         [ 33,  50,  74],
         ...,
         [ 41,  82, 139],
         [ 47,  82, 131],
         [ 65, 109, 170]],

        [[ 47,  66, 105],
         [ 39,  58,  91],
         [ 29,  50,  88],
         ...,
         [ 25,  59,  95],
         [ 18,  48,  61],
         [ 27,  65,  79]],

        [[ 49,  72, 116],
         [ 37,  65,  98],
         [ 28,  58, 101],
         ...,
         [ 31,  62,  93],
         [ 24,  54,  74],
         [ 21,  55,  74]],

        ...,

        [[ 30,  51,  94],
         [ 36,  55,  90],
         [ 30,  48,  82],
         ...,
         [ 33,  68,  94],
         [ 38,  66,  99],
         [ 39,  70,  99]],

        [[ 42,  60,  97],
         [ 43,  58, 100],
         [ 50,  63, 105],
         ...,
         [ 41,  74, 104],
         [ 55,  80, 116],
         [ 44,  71, 104]],

        [[ 52,  77, 115],
         [ 49,  73, 122],
         [ 54,  78, 123],
         ...,
         [ 46,  83, 113],
        

In [65]:
john_label #not already one hot

array([26, 15, 13, ..., 39,  1, 10])

In [71]:
X_train2, X_val2, y_train2, y_val2 = train_test_split(john_data, john_label, test_size=0.3, random_state=42, shuffle=True)

X_train2 = X_train2/255
X_val = X_val2/255

print("X_train2.shape", X_train2.shape)
print("X_valid2.shape", X_val2.shape)
print("y_train2.shape", y_train2.shape)
print("y_valid2.shape", y_val2.shape)

X_train2.shape (27446, 30, 30, 3)
X_valid2.shape (11763, 30, 30, 3)
y_train2.shape (27446,)
y_valid2.shape (11763,)


In [72]:
X_train2

array([[[[0.07058824, 0.08235294, 0.09803922],
         [0.07058824, 0.08235294, 0.09019608],
         [0.06666667, 0.0745098 , 0.07843137],
         ...,
         [0.0627451 , 0.05490196, 0.07058824],
         [0.0627451 , 0.05490196, 0.06666667],
         [0.0627451 , 0.05490196, 0.06666667]],

        [[0.07058824, 0.0745098 , 0.08627451],
         [0.07058824, 0.0745098 , 0.08235294],
         [0.07843137, 0.07843137, 0.08627451],
         ...,
         [0.0627451 , 0.05098039, 0.0627451 ],
         [0.06666667, 0.05490196, 0.06666667],
         [0.0745098 , 0.0627451 , 0.0745098 ]],

        [[0.06666667, 0.07058824, 0.07843137],
         [0.0627451 , 0.06666667, 0.0745098 ],
         [0.07058824, 0.0745098 , 0.07843137],
         ...,
         [0.0627451 , 0.0627451 , 0.0627451 ],
         [0.0627451 , 0.05882353, 0.06666667],
         [0.0627451 , 0.05490196, 0.06666667]],

        ...,

        [[0.30980392, 0.24705882, 0.45098039],
         [0.23137255, 0.27843137, 0.36078431]

In [73]:
y_train2

array([12, 18,  7, ...,  8,  4,  8])

In [74]:
y_train2 = keras.utils.to_categorical(y_train2, NUM_CATEGORIES)
y_val2 = keras.utils.to_categorical(y_val2, NUM_CATEGORIES)

print(y_train2.shape)
print(y_val2.shape)

(27446, 43)
(11763, 43)


In [75]:
y_train2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# Checking if y_train from johns is same as this y_train2 one hot encode

In [25]:
if john_label.all() == y_train2.all():
    print("identical")
else:
    print("not the same")

identical


In [26]:
if john_data.all() == X_train2.all():
    print("identical")
else:
    print("not the same")

identical


In [76]:
model = keras.models.Sequential([    
    keras.layers.Conv2D(filters=16, kernel_size=(3,3), activation='relu', input_shape=(IMG_HEIGHT,IMG_WIDTH,channels)),
    keras.layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu'),
    keras.layers.MaxPool2D(pool_size=(2, 2)),
    keras.layers.BatchNormalization(axis=-1),
    
    keras.layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu'),
    keras.layers.Conv2D(filters=128, kernel_size=(3,3), activation='relu'),
    keras.layers.MaxPool2D(pool_size=(2, 2)),
    keras.layers.BatchNormalization(axis=-1),
    
    keras.layers.Flatten(),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(rate=0.5),
    
    keras.layers.Dense(43, activation='softmax')
])

In [77]:
lr = 0.001
epochs = 1

opt = tf.keras.optimizers.legacy.Adam(lr=lr, decay=lr / (epochs * 0.5))
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

C:\Users\Team Knowhow\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [ ]:
aug = ImageDataGenerator(
    rotation_range=10,
    zoom_range=0.15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.15,
    horizontal_flip=False,
    vertical_flip=False,
    fill_mode="nearest")

history = model.fit(aug.flow(X_train2, y_train2, batch_size=32), epochs=epochs, validation_data=(X_val2, y_val2))

659/858 [======================>.......] - ETA: 22s - loss: 1.2880 - accuracy: 0.6540

In [31]:
test_data2 = np.load('30_original_test_data.npy')
test_labels2 = np.load('30_original_test_labels.npy')

In [42]:
test_data2 = test_data2/255


In [36]:
pred = np.argmax(model.predict(test_data2), axis=-1)


395/395 [==============================] - 13s 31ms/step


In [43]:
test_labels2

array([42., 42., 42., ..., 42., 42., 42.])

In [44]:
#Accuracy with the test data
print('Test Data accuracy: ',accuracy_score(test_labels2, pred)*100)

Test Data accuracy:  0.5859065716547902


In [37]:
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(test_labels2, pred)

In [38]:
from sklearn.metrics import classification_report

print(classification_report(test_labels2, pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         0
          17       0.00    

C:\Users\Team Knowhow\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Team Knowhow\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Team Knowhow\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Bright-dark filter dataset through the CNN

In [2]:
training_data = np.load('array_pixels_training.npy')
training_label = np.load('array_pixels_label.npy')


In [3]:
training_data.shape

(95460, 32, 32, 3)

In [5]:
X_train, X_val, y_train, y_val = train_test_split(training_data, training_label, test_size=0.3, random_state=42, shuffle=True)

X_train = X_train 
X_val = X_val

print("X_train.shape", X_train.shape)
print("X_valid.shape", X_val.shape)
print("y_train.shape", y_train.shape)
print("y_valid.shape", y_val.shape)

X_train.shape (66822, 32, 32, 3)
X_valid.shape (28638, 32, 32, 3)
y_train.shape (66822,)
y_valid.shape (28638,)


In [6]:
y_train = keras.utils.to_categorical(y_train, NUM_CATEGORIES)
y_val = keras.utils.to_categorical(y_val, NUM_CATEGORIES)

print(y_train.shape)
print(y_val.shape)

(66822, 43)
(28638, 43)


In [7]:
model = keras.models.Sequential([    
    keras.layers.Conv2D(filters=16, kernel_size=(3,3), activation='relu', input_shape=(32,32,3)),
    keras.layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu'),
    keras.layers.MaxPool2D(pool_size=(2, 2)),
    keras.layers.BatchNormalization(axis=-1),
    
    keras.layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu'),
    keras.layers.Conv2D(filters=128, kernel_size=(3,3), activation='relu'),
    keras.layers.MaxPool2D(pool_size=(2, 2)),
    keras.layers.BatchNormalization(axis=-1),
    
    keras.layers.Flatten(),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(rate=0.5),
    
    keras.layers.Dense(43, activation='softmax')
])

In [8]:
lr = 0.001
epochs = 1

opt = tf.keras.optimizers.legacy.Adam(lr=lr, decay=lr / (epochs * 0.5))
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

C:\Users\Team Knowhow\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [9]:
aug = ImageDataGenerator(
    rotation_range=10,
    zoom_range=0.15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.15,
    horizontal_flip=False,
    vertical_flip=False,
    fill_mode="nearest")

history = model.fit(aug.flow(X_train, y_train, batch_size=32), epochs=epochs, validation_data=(X_val, y_val))

2089/2089 [==============================] - 213s 101ms/step - loss: 4.2762 - accuracy: 0.0235 - val_loss: 3.8165 - val_accuracy: 0.0224


In [10]:
test_data = np.load('array_pixels_test.npy')
test_labels = np.load('array_test_label.npy')

In [11]:

X_test = test_data

pred = np.argmax(model.predict(X_test), axis=-1)

#Accuracy with the test data
print('Test Data accuracy: ',accuracy_score(test_labels, pred)*100)

395/395 [==============================] - 8s 20ms/step
Test Data accuracy:  0.023752969121140142


In [12]:
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(test_labels, pred)

In [13]:
from sklearn.metrics import classification_report

print(classification_report(test_labels, pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          17       0.00      0.00      0.00         0
          18       0.00    

C:\Users\Team Knowhow\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Team Knowhow\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Team Knowhow\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
